version: '3.5'
services:
  backend-api:
    build:
      context: ./backend-api
      target: build
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/key.json"
      FRONTEND_HOST: "http://localhost:8081"
      PROJECT_ID: "testing-190927-golang"
    volumes:
      - ./backend-api:/go/app
      - ~/.config/gcloud/application_default_credentials.json:/key.json:ro
    command: ["realize", "start", "--run"]
    ports:
      - 8080:8080

  frontend:
    build: ./frontend
    ports:
      - 8081:8081
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: "development"
      VUE_APP_DEVELOPMENT_BACKENDHOST: "http://localhost:8080"
    command: ["npm", "run", "serve"]
